// Generated by Framer (0f5ea8b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import CardWrap from "https://framerusercontent.com/modules/kIADeDvbfMkQy3kzagUK/gDRdqXbEVYZ9BBui118C/S1fWa2Wkj.js";
const CardWrapFonts = getFonts(CardWrap);
const SmartComponentScopedContainerWithFX = withFX(
  SmartComponentScopedContainer,
);
const cycleOrder = ["NJ2mYgZiy", "TpR7tx10J", "yEk2784iI"];
const serializationHash = "framer-gxEXg";
const variantClassNames = {
  NJ2mYgZiy: "framer-v-1qbd4kt",
  TpR7tx10J: "framer-v-151ums2",
  yEk2784iI: "framer-v-qq7o9z",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const FQrrRv3Xn = undefined;
const KoyyAx70J = undefined;
const tWgYBJMqd = undefined;
const u5H2OkbTf = undefined;
const TkbnSs_QY = undefined;
const YsJaFxlxJ = undefined;
const IjTSo9v8a = undefined;
const q5JoCbVah = undefined;
const NQUvPF0Ed = undefined;
const G07aaR7mP = undefined;
const kVkM2Vize = undefined;
const c9JDpgSaj = undefined;
const bT7VFLkwN = undefined;
const tUK9QKRfm = undefined;
const MAolvu_Uz = undefined;
const jbnk6z7au = undefined;
const lb_NSLyCc = undefined;
const gyWOQ3Y5L = undefined;
const I1EwIDyNd = undefined;
const qk_7shWiw = undefined;
const yz6Azgs5e = undefined;
const QZeLnSM0X = undefined;
const WrxRQnwtW = undefined;
const kmAs_AL71 = undefined;
const ry4V6X50J = undefined;
const uJ3k_3FrD = undefined;
const setTkbnSs_QY = undefined;
const setYsJaFxlxJ = undefined;
const setNQUvPF0Ed = undefined;
const setG07aaR7mP = undefined;
const setbT7VFLkwN = undefined;
const settUK9QKRfm = undefined;
const setlb_NSLyCc = undefined;
const setgyWOQ3Y5L = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transition2 = {
  delay: 0,
  duration: 1.5,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: -8,
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const animation1 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 5,
};
const animation2 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: -6,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  Desktop: "NJ2mYgZiy",
  Phone: "yEk2784iI",
  Tablet: "TpR7tx10J",
};
const Variants = motion.create(React.Fragment);
const useStateVariable = (externalState, setExternalState) => {
  const [internalState, setInternalState] = React.useState(externalState);
  const [previousExternalState, setPreviousExternalState] =
    React.useState(externalState);
  if (setExternalState) {
    return [externalState, setExternalState];
  }
  if (externalState !== previousExternalState) {
    setInternalState(externalState);
    setPreviousExternalState(externalState);
  }
  return [internalState, setInternalState];
};
const getProps = ({
  _1ScrollSection1,
  _1ScrollSection2,
  _1ScrollSection3,
  _1ScrollSection4,
  _2ScrollSection1,
  _2ScrollSection2,
  _2ScrollSection3,
  _2ScrollSection4,
  _3ScrollSection1,
  _3ScrollSection2,
  _3ScrollSection3,
  _3ScrollSection4,
  cTAButton,
  height,
  id,
  image1,
  image2,
  image3,
  link1,
  link2,
  link3,
  newTabLinkOpen,
  serviceContent1,
  serviceContent2,
  serviceContent3,
  serviceName1,
  serviceName2,
  serviceName3,
  width,
  ...props
}) => {
  return {
    ...props,
    bT7VFLkwN: serviceName3 ?? props.bT7VFLkwN ?? "Creative Production",
    c9JDpgSaj: link2 ?? props.c9JDpgSaj,
    FQrrRv3Xn: _3ScrollSection1 ?? props.FQrrRv3Xn,
    G07aaR7mP:
      serviceContent2 ??
      props.G07aaR7mP ??
      "Design and develop modern websites with seamless experiences that engage visitors and turn interactions into growth at scale.",
    gyWOQ3Y5L: newTabLinkOpen ?? props.gyWOQ3Y5L ?? true,
    I1EwIDyNd: _2ScrollSection1 ?? props.I1EwIDyNd,
    IjTSo9v8a: image1 ??
      props.IjTSo9v8a ?? {
        pixelHeight: 755,
        pixelWidth: 686,
        src: "https://framerusercontent.com/images/tUkDeSIXGHUoQm8mfXzM7PvqB8Q.png?width=686&height=755",
        srcSet:
          "https://framerusercontent.com/images/tUkDeSIXGHUoQm8mfXzM7PvqB8Q.png?width=686&height=755 686w",
      },
    jbnk6z7au: link3 ?? props.jbnk6z7au,
    kmAs_AL71: _1ScrollSection2 ?? props.kmAs_AL71,
    KoyyAx70J: _3ScrollSection2 ?? props.KoyyAx70J,
    kVkM2Vize: image2 ??
      props.kVkM2Vize ?? {
        pixelHeight: 673,
        pixelWidth: 1200,
        src: "https://framerusercontent.com/images/A4kZ4JKrKRQB47BZsV6CXyJCwA.png?width=1200&height=673",
        srcSet:
          "https://framerusercontent.com/images/A4kZ4JKrKRQB47BZsV6CXyJCwA.png?scale-down-to=512&width=1200&height=673 512w,https://framerusercontent.com/images/A4kZ4JKrKRQB47BZsV6CXyJCwA.png?scale-down-to=1024&width=1200&height=673 1024w,https://framerusercontent.com/images/A4kZ4JKrKRQB47BZsV6CXyJCwA.png?width=1200&height=673 1200w",
      },
    lb_NSLyCc: cTAButton ?? props.lb_NSLyCc ?? "Know More",
    MAolvu_Uz: image3 ??
      props.MAolvu_Uz ?? {
        pixelHeight: 799,
        pixelWidth: 1200,
        src: "https://framerusercontent.com/images/aX7OzhXTeeu9KoHilGJmEuZTbY.png?width=1200&height=799",
        srcSet:
          "https://framerusercontent.com/images/aX7OzhXTeeu9KoHilGJmEuZTbY.png?scale-down-to=512&width=1200&height=799 512w,https://framerusercontent.com/images/aX7OzhXTeeu9KoHilGJmEuZTbY.png?scale-down-to=1024&width=1200&height=799 1024w,https://framerusercontent.com/images/aX7OzhXTeeu9KoHilGJmEuZTbY.png?width=1200&height=799 1200w",
      },
    NQUvPF0Ed: serviceName2 ?? props.NQUvPF0Ed ?? "Web Design & Dev",
    q5JoCbVah: link1 ?? props.q5JoCbVah,
    qk_7shWiw: _2ScrollSection2 ?? props.qk_7shWiw,
    QZeLnSM0X: _2ScrollSection4 ?? props.QZeLnSM0X,
    ry4V6X50J: _1ScrollSection3 ?? props.ry4V6X50J,
    TkbnSs_QY: serviceName1 ?? props.TkbnSs_QY ?? "Branding & Identity",
    tUK9QKRfm:
      serviceContent3 ??
      props.tUK9QKRfm ??
      "Create impactful visual content through storytelling and production that captures attention across every platform every day.",
    tWgYBJMqd: _3ScrollSection3 ?? props.tWgYBJMqd,
    u5H2OkbTf: _3ScrollSection4 ?? props.u5H2OkbTf,
    uJ3k_3FrD: _1ScrollSection4 ?? props.uJ3k_3FrD,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "NJ2mYgZiy",
    WrxRQnwtW: _1ScrollSection1 ?? props.WrxRQnwtW,
    YsJaFxlxJ:
      serviceContent1 ??
      props.YsJaFxlxJ ??
      "Build distinctive brands through strategy, identity, and messaging that create trust and meaningful audience connections now.",
    yz6Azgs5e: _2ScrollSection3 ?? props.yz6Azgs5e,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    TkbnSs_QY: externalTkbnSs_QY,
    onTkbnSs_QYChange: setExternalTkbnSs_QY,
    YsJaFxlxJ: externalYsJaFxlxJ,
    onYsJaFxlxJChange: setExternalYsJaFxlxJ,
    IjTSo9v8a,
    q5JoCbVah,
    NQUvPF0Ed: externalNQUvPF0Ed,
    onNQUvPF0EdChange: setExternalNQUvPF0Ed,
    G07aaR7mP: externalG07aaR7mP,
    onG07aaR7mPChange: setExternalG07aaR7mP,
    kVkM2Vize,
    c9JDpgSaj,
    bT7VFLkwN: externalbT7VFLkwN,
    onbT7VFLkwNChange: setExternalbT7VFLkwN,
    tUK9QKRfm: externaltUK9QKRfm,
    ontUK9QKRfmChange: setExternaltUK9QKRfm,
    MAolvu_Uz,
    lb_NSLyCc: externallb_NSLyCc,
    onlb_NSLyCcChange: setExternallb_NSLyCc,
    jbnk6z7au,
    gyWOQ3Y5L: externalgyWOQ3Y5L,
    ongyWOQ3Y5LChange: setExternalgyWOQ3Y5L,
    WrxRQnwtW,
    kmAs_AL71,
    ry4V6X50J,
    uJ3k_3FrD,
    I1EwIDyNd,
    qk_7shWiw,
    yz6Azgs5e,
    QZeLnSM0X,
    FQrrRv3Xn,
    KoyyAx70J,
    tWgYBJMqd,
    u5H2OkbTf,
    ...restProps
  } = getProps(props);
  const [TkbnSs_QY, setTkbnSs_QY] = useStateVariable(
    externalTkbnSs_QY,
    setExternalTkbnSs_QY,
  );
  const [YsJaFxlxJ, setYsJaFxlxJ] = useStateVariable(
    externalYsJaFxlxJ,
    setExternalYsJaFxlxJ,
  );
  const [NQUvPF0Ed, setNQUvPF0Ed] = useStateVariable(
    externalNQUvPF0Ed,
    setExternalNQUvPF0Ed,
  );
  const [G07aaR7mP, setG07aaR7mP] = useStateVariable(
    externalG07aaR7mP,
    setExternalG07aaR7mP,
  );
  const [bT7VFLkwN, setbT7VFLkwN] = useStateVariable(
    externalbT7VFLkwN,
    setExternalbT7VFLkwN,
  );
  const [tUK9QKRfm, settUK9QKRfm] = useStateVariable(
    externaltUK9QKRfm,
    setExternaltUK9QKRfm,
  );
  const [lb_NSLyCc, setlb_NSLyCc] = useStateVariable(
    externallb_NSLyCc,
    setExternallb_NSLyCc,
  );
  const [gyWOQ3Y5L, setgyWOQ3Y5L] = useStateVariable(
    externalgyWOQ3Y5L,
    setExternalgyWOQ3Y5L,
  );
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "NJ2mYgZiy",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1qbd4kt",
            className,
            classNames,
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "NJ2mYgZiy",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              TpR7tx10J: { "data-framer-name": "Tablet" },
              yEk2784iI: { "data-framer-name": "Phone" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-j600ed",
            "data-framer-name": "Card Wrap",
            layoutDependency: layoutDependency,
            layoutId: "GnHm1vzvG",
            style: { scale: 1 },
            variants: { TpR7tx10J: { scale: 0.9 }, yEk2784iI: { scale: 1 } },
            children: [
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                height: 400,
                y:
                  (componentViewport?.y || 0) +
                  (30 + ((componentViewport?.height || 800) - 60 - 400) / 2) +
                  -52,
                ...addPropertyOverrides(
                  {
                    yEk2784iI: {
                      y:
                        (componentViewport?.y || 0) +
                        (30 +
                          ((componentViewport?.height || 1340) - 60 - 1280) /
                            2) +
                        0 +
                        880,
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
                children: /*#__PURE__*/ _jsx(
                  SmartComponentScopedContainerWithFX,
                  {
                    __framer__loop: animation,
                    __framer__loopEffectEnabled: true,
                    __framer__loopPauseOffscreen: true,
                    __framer__loopRepeatDelay: 1,
                    __framer__loopRepeatType: "mirror",
                    __framer__loopTransition: transition2,
                    __framer__spring: {
                      damping: 60,
                      delay: 0,
                      duration: 0.3,
                      ease: [0.44, 0, 0.56, 1],
                      mass: 1,
                      stagger: 0,
                      stiffness: 500,
                      type: "spring",
                    },
                    __framer__styleTransformEffectEnabled: true,
                    __framer__transformTargets: [
                      {
                        target: {
                          opacity: 1,
                          rotate: 0,
                          rotateX: 0,
                          rotateY: 0,
                          scale: 0.8,
                          skewX: 0,
                          skewY: 0,
                          x: 0,
                          y: -20,
                        },
                      },
                      {
                        ref: FQrrRv3Xn,
                        target: {
                          opacity: 1,
                          rotate: 0,
                          rotateX: 0,
                          rotateY: 0,
                          scale: 0.9,
                          skewX: 0,
                          skewY: 0,
                          x: 0,
                          y: 270,
                        },
                      },
                      {
                        ref: KoyyAx70J,
                        target: {
                          opacity: 1,
                          rotate: 0,
                          rotateX: 0,
                          rotateY: 0,
                          scale: 1,
                          skewX: 0,
                          skewY: 0,
                          x: 0,
                          y: 230,
                        },
                      },
                      {
                        ref: tWgYBJMqd,
                        target: {
                          opacity: 1,
                          rotate: -2,
                          rotateX: 0,
                          rotateY: 0,
                          scale: 1,
                          skewX: 0,
                          skewY: 0,
                          x: 0,
                          y: 92,
                        },
                      },
                      {
                        ref: u5H2OkbTf,
                        target: {
                          opacity: 1,
                          rotate: -7,
                          rotateX: 0,
                          rotateY: -180,
                          scale: 1,
                          skewX: 0,
                          skewY: 0,
                          x: 610,
                          y: 52,
                        },
                      },
                    ],
                    __framer__transformTrigger: "onScrollTarget",
                    __framer__transformViewportThreshold: 1,
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    className: "framer-8xdv0f-container",
                    "data-framer-name": "Card Wrap 3",
                    layoutDependency: layoutDependency,
                    layoutId: "bY4P1sx3I-container",
                    name: "Card Wrap 3",
                    nodeId: "bY4P1sx3I",
                    rendersWithMotion: true,
                    scopeId: "wKkGQAcuS",
                    style: { originX: 0, rotate: 7 },
                    variants: { yEk2784iI: { originX: undefined, rotate: -2 } },
                    ...addPropertyOverrides(
                      {
                        TpR7tx10J: {
                          __framer__transformTargets: [
                            {
                              target: {
                                opacity: 1,
                                rotate: 0,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 0.8,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: -20,
                              },
                            },
                            {
                              ref: FQrrRv3Xn,
                              target: {
                                opacity: 1,
                                rotate: 0,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 0.9,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: 270,
                              },
                            },
                            {
                              ref: KoyyAx70J,
                              target: {
                                opacity: 1,
                                rotate: 0,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 1,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: 230,
                              },
                            },
                            {
                              ref: tWgYBJMqd,
                              target: {
                                opacity: 1,
                                rotate: -2,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 1,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: 92,
                              },
                            },
                            {
                              ref: u5H2OkbTf,
                              target: {
                                opacity: 1,
                                rotate: -7,
                                rotateX: 0,
                                rotateY: -180,
                                scale: 1,
                                skewX: 0,
                                skewY: 0,
                                x: 550,
                                y: 52,
                              },
                            },
                          ],
                        },
                        yEk2784iI: {
                          __framer__loopEffectEnabled: undefined,
                          __framer__styleTransformEffectEnabled: undefined,
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                    children: /*#__PURE__*/ _jsx(CardWrap, {
                      bHAFaIL6x: bT7VFLkwN,
                      ChqSxOsiW: NQUvPF0Ed,
                      E3heAdqO0: toResponsiveImage(MAolvu_Uz),
                      F5dxZeWeY: toResponsiveImage(IjTSo9v8a),
                      fALVpL9rl: TkbnSs_QY,
                      G8Lsht7iZ: YsJaFxlxJ,
                      gN53GihA5: q5JoCbVah,
                      H9QNOLhMo: gyWOQ3Y5L,
                      height: "100%",
                      IBaWzeI9Z: tUK9QKRfm,
                      id: "bY4P1sx3I",
                      layoutId: "bY4P1sx3I",
                      n3_0W7muj: G07aaR7mP,
                      name: "Card Wrap 3",
                      onbHAFaIL6xChange: setbT7VFLkwN,
                      onChqSxOsiWChange: setNQUvPF0Ed,
                      onfALVpL9rlChange: setTkbnSs_QY,
                      onG8Lsht7iZChange: setYsJaFxlxJ,
                      onH9QNOLhMoChange: setgyWOQ3Y5L,
                      onIBaWzeI9ZChange: settUK9QKRfm,
                      onn3_0W7mujChange: setG07aaR7mP,
                      onum_tX3Ry9Change: setlb_NSLyCc,
                      qYGkNGCLz: toResponsiveImage(kVkM2Vize),
                      STJFnlkMo: jbnk6z7au,
                      um_tX3Ry9: lb_NSLyCc,
                      V7HSEOkmb: c9JDpgSaj,
                      variant: matchVariant("iSoBmCH55"),
                      width: "100%",
                      ...addPropertyOverrides(
                        { yEk2784iI: { variant: matchVariant("cSK_6_6ak") } },
                        baseVariant,
                        gestureVariant,
                      ),
                    }),
                  },
                ),
              }),
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                height: 400,
                y:
                  (componentViewport?.y || 0) +
                  (30 + ((componentViewport?.height || 800) - 60 - 400) / 2) +
                  0,
                ...addPropertyOverrides(
                  {
                    yEk2784iI: {
                      y:
                        (componentViewport?.y || 0) +
                        (30 +
                          ((componentViewport?.height || 1340) - 60 - 1280) /
                            2) +
                        0 +
                        440,
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
                children: /*#__PURE__*/ _jsx(
                  SmartComponentScopedContainerWithFX,
                  {
                    __framer__loop: animation1,
                    __framer__loopEffectEnabled: true,
                    __framer__loopPauseOffscreen: true,
                    __framer__loopRepeatDelay: 0.25,
                    __framer__loopRepeatType: "mirror",
                    __framer__loopTransition: transition2,
                    __framer__spring: {
                      bounce: 0.2,
                      damping: 60,
                      delay: 0,
                      duration: 0.3,
                      durationBasedSpring: true,
                      ease: [0.44, 0, 0.56, 1],
                      mass: 1,
                      stagger: 0,
                      stiffness: 500,
                      type: "spring",
                    },
                    __framer__styleTransformEffectEnabled: true,
                    __framer__transformTargets: [
                      {
                        target: {
                          opacity: 1,
                          rotate: 0,
                          rotateX: 0,
                          rotateY: 0,
                          scale: 0.8,
                          skewX: 0,
                          skewY: 0,
                          x: 0,
                          y: 0,
                        },
                      },
                      {
                        ref: I1EwIDyNd,
                        target: {
                          opacity: 1,
                          rotate: 0,
                          rotateX: 0,
                          rotateY: 0,
                          scale: 0.9,
                          skewX: 0,
                          skewY: 0,
                          x: 0,
                          y: 210,
                        },
                      },
                      {
                        ref: qk_7shWiw,
                        target: {
                          opacity: 1,
                          rotate: 0,
                          rotateX: 0,
                          rotateY: 0,
                          scale: 1,
                          skewX: 0,
                          skewY: 0,
                          x: 0,
                          y: 140,
                        },
                      },
                      {
                        ref: yz6Azgs5e,
                        target: {
                          opacity: 1,
                          rotate: -2,
                          rotateX: 0,
                          rotateY: 0,
                          scale: 1,
                          skewX: 0,
                          skewY: 0,
                          x: 0,
                          y: 20,
                        },
                      },
                      {
                        ref: QZeLnSM0X,
                        target: {
                          opacity: 1,
                          rotate: -3,
                          rotateX: 0,
                          rotateY: -180,
                          scale: 1,
                          skewX: 0,
                          skewY: 0,
                          x: 290,
                          y: 0,
                        },
                      },
                    ],
                    __framer__transformTrigger: "onScrollTarget",
                    __framer__transformViewportThreshold: 1,
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    className: "framer-jxagyo-container",
                    "data-framer-name": "Card Wrap 2",
                    layoutDependency: layoutDependency,
                    layoutId: "oFZ_l4b8b-container",
                    name: "Card Wrap 2",
                    nodeId: "oFZ_l4b8b",
                    rendersWithMotion: true,
                    scopeId: "wKkGQAcuS",
                    style: { originX: 0, rotate: 3, z: 1 },
                    variants: { yEk2784iI: { originX: undefined, rotate: 2 } },
                    ...addPropertyOverrides(
                      {
                        yEk2784iI: {
                          __framer__loopEffectEnabled: undefined,
                          __framer__styleTransformEffectEnabled: undefined,
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                    children: /*#__PURE__*/ _jsx(CardWrap, {
                      bHAFaIL6x: bT7VFLkwN,
                      ChqSxOsiW: NQUvPF0Ed,
                      E3heAdqO0: toResponsiveImage(MAolvu_Uz),
                      F5dxZeWeY: toResponsiveImage(IjTSo9v8a),
                      fALVpL9rl: TkbnSs_QY,
                      G8Lsht7iZ: YsJaFxlxJ,
                      gN53GihA5: q5JoCbVah,
                      H9QNOLhMo: gyWOQ3Y5L,
                      height: "100%",
                      IBaWzeI9Z: tUK9QKRfm,
                      id: "oFZ_l4b8b",
                      layoutId: "oFZ_l4b8b",
                      n3_0W7muj: G07aaR7mP,
                      name: "Card Wrap 2",
                      onbHAFaIL6xChange: setbT7VFLkwN,
                      onChqSxOsiWChange: setNQUvPF0Ed,
                      onfALVpL9rlChange: setTkbnSs_QY,
                      onG8Lsht7iZChange: setYsJaFxlxJ,
                      onH9QNOLhMoChange: setgyWOQ3Y5L,
                      onIBaWzeI9ZChange: settUK9QKRfm,
                      onn3_0W7mujChange: setG07aaR7mP,
                      onum_tX3Ry9Change: setlb_NSLyCc,
                      qYGkNGCLz: toResponsiveImage(kVkM2Vize),
                      STJFnlkMo: jbnk6z7au,
                      um_tX3Ry9: lb_NSLyCc,
                      V7HSEOkmb: c9JDpgSaj,
                      variant: matchVariant("NwXfoNbge"),
                      width: "100%",
                      ...addPropertyOverrides(
                        { yEk2784iI: { variant: matchVariant("qHGk0G_bg") } },
                        baseVariant,
                        gestureVariant,
                      ),
                    }),
                  },
                ),
              }),
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                height: 400,
                y:
                  (componentViewport?.y || 0) +
                  (30 + ((componentViewport?.height || 800) - 60 - 400) / 2) +
                  400 -
                  340,
                ...addPropertyOverrides(
                  {
                    yEk2784iI: {
                      y:
                        (componentViewport?.y || 0) +
                        (30 +
                          ((componentViewport?.height || 1340) - 60 - 1280) /
                            2) +
                        0 +
                        0,
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
                children: /*#__PURE__*/ _jsx(
                  SmartComponentScopedContainerWithFX,
                  {
                    __framer__loop: animation2,
                    __framer__loopEffectEnabled: true,
                    __framer__loopPauseOffscreen: true,
                    __framer__loopRepeatDelay: 0,
                    __framer__loopRepeatType: "mirror",
                    __framer__loopTransition: transition2,
                    __framer__spring: {
                      damping: 60,
                      delay: 0,
                      duration: 0.3,
                      ease: [0.44, 0, 0.56, 1],
                      mass: 1,
                      stagger: 0,
                      stiffness: 500,
                      type: "spring",
                    },
                    __framer__styleTransformEffectEnabled: true,
                    __framer__transformTargets: [
                      {
                        target: {
                          opacity: 1,
                          rotate: 0,
                          rotateX: 0,
                          rotateY: 0,
                          scale: 0.8,
                          skewX: 0,
                          skewY: 0,
                          x: 0,
                          y: 20,
                        },
                      },
                      {
                        ref: WrxRQnwtW,
                        target: {
                          opacity: 1,
                          rotate: 0,
                          rotateX: 0,
                          rotateY: 0,
                          scale: 0.9,
                          skewX: 0,
                          skewY: 0,
                          x: 0,
                          y: 170,
                        },
                      },
                      {
                        ref: kmAs_AL71,
                        target: {
                          opacity: 1,
                          rotate: 0,
                          rotateX: 0,
                          rotateY: 0,
                          scale: 1,
                          skewX: 0,
                          skewY: 0,
                          x: 0,
                          y: 70,
                        },
                      },
                      {
                        ref: ry4V6X50J,
                        target: {
                          opacity: 1,
                          rotate: 1,
                          rotateX: 0,
                          rotateY: 0,
                          scale: 1,
                          skewX: 0,
                          skewY: 0,
                          x: 0,
                          y: -30,
                        },
                      },
                      {
                        ref: uJ3k_3FrD,
                        target: {
                          opacity: 1,
                          rotate: 4,
                          rotateX: 0,
                          rotateY: -180,
                          scale: 1,
                          skewX: 0,
                          skewY: 0,
                          x: -30,
                          y: -60,
                        },
                      },
                    ],
                    __framer__transformTrigger: "onScrollTarget",
                    __framer__transformViewportThreshold: 1,
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    className: "framer-12dkhc1-container",
                    "data-framer-name": "Card Wrap 1",
                    layoutDependency: layoutDependency,
                    layoutId: "xVo6_Bqdk-container",
                    name: "Card Wrap 1",
                    nodeId: "xVo6_Bqdk",
                    rendersWithMotion: true,
                    scopeId: "wKkGQAcuS",
                    style: { originX: 0, rotate: -4, z: 2 },
                    variants: { yEk2784iI: { originX: undefined, rotate: -3 } },
                    ...addPropertyOverrides(
                      {
                        TpR7tx10J: {
                          __framer__transformTargets: [
                            {
                              target: {
                                opacity: 1,
                                rotate: 0,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 0.8,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: 20,
                              },
                            },
                            {
                              ref: WrxRQnwtW,
                              target: {
                                opacity: 1,
                                rotate: 0,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 0.9,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: 170,
                              },
                            },
                            {
                              ref: kmAs_AL71,
                              target: {
                                opacity: 1,
                                rotate: 0,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 1,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: 70,
                              },
                            },
                            {
                              ref: ry4V6X50J,
                              target: {
                                opacity: 1,
                                rotate: 1,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 1,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: -30,
                              },
                            },
                            {
                              ref: uJ3k_3FrD,
                              target: {
                                opacity: 1,
                                rotate: 4,
                                rotateX: 0,
                                rotateY: -180,
                                scale: 1,
                                skewX: 0,
                                skewY: 0,
                                x: 30,
                                y: -60,
                              },
                            },
                          ],
                        },
                        yEk2784iI: {
                          __framer__loopEffectEnabled: undefined,
                          __framer__styleTransformEffectEnabled: undefined,
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                    children: /*#__PURE__*/ _jsx(CardWrap, {
                      bHAFaIL6x: bT7VFLkwN,
                      ChqSxOsiW: NQUvPF0Ed,
                      E3heAdqO0: toResponsiveImage(MAolvu_Uz),
                      F5dxZeWeY: toResponsiveImage(IjTSo9v8a),
                      fALVpL9rl: TkbnSs_QY,
                      G8Lsht7iZ: YsJaFxlxJ,
                      gN53GihA5: q5JoCbVah,
                      H9QNOLhMo: gyWOQ3Y5L,
                      height: "100%",
                      IBaWzeI9Z: tUK9QKRfm,
                      id: "xVo6_Bqdk",
                      layoutId: "xVo6_Bqdk",
                      n3_0W7muj: G07aaR7mP,
                      name: "Card Wrap 1",
                      onbHAFaIL6xChange: setbT7VFLkwN,
                      onChqSxOsiWChange: setNQUvPF0Ed,
                      onfALVpL9rlChange: setTkbnSs_QY,
                      onG8Lsht7iZChange: setYsJaFxlxJ,
                      onH9QNOLhMoChange: setgyWOQ3Y5L,
                      onIBaWzeI9ZChange: settUK9QKRfm,
                      onn3_0W7mujChange: setG07aaR7mP,
                      onum_tX3Ry9Change: setlb_NSLyCc,
                      qYGkNGCLz: toResponsiveImage(kVkM2Vize),
                      STJFnlkMo: jbnk6z7au,
                      um_tX3Ry9: lb_NSLyCc,
                      V7HSEOkmb: c9JDpgSaj,
                      variant: matchVariant("jtoJiMks3"),
                      width: "100%",
                      ...addPropertyOverrides(
                        { yEk2784iI: { variant: matchVariant("LrkCYv9bP") } },
                        baseVariant,
                        gestureVariant,
                      ),
                    }),
                  },
                ),
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-gxEXg.framer-1bm6dzr, .framer-gxEXg .framer-1bm6dzr { display: block; }",
  ".framer-gxEXg.framer-1qbd4kt { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; min-height: calc(var(--framer-viewport-height, 100vh) * 1); overflow: visible; padding: 30px 20px 30px 20px; position: relative; width: 1200px; }",
  ".framer-gxEXg .framer-j600ed { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 52px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; transform-style: preserve-3d; width: min-content; }",
  ".framer-gxEXg .framer-8xdv0f-container { flex: none; height: auto; position: absolute; right: -59px; top: -52px; transform-style: preserve-3d; width: auto; z-index: 1; }",
  ".framer-gxEXg .framer-jxagyo-container { flex: none; height: auto; position: relative; transform-style: preserve-3d; width: auto; z-index: 2; }",
  ".framer-gxEXg .framer-12dkhc1-container { bottom: -60px; flex: none; height: auto; left: -60px; position: absolute; transform-style: preserve-3d; width: auto; z-index: 3; }",
  ".framer-gxEXg.framer-v-151ums2.framer-1qbd4kt { width: 810px; }",
  ".framer-gxEXg.framer-v-qq7o9z.framer-1qbd4kt { width: 390px; }",
  ".framer-gxEXg.framer-v-qq7o9z .framer-j600ed { flex-direction: column; gap: 40px; }",
  ".framer-gxEXg.framer-v-qq7o9z .framer-8xdv0f-container { order: 2; position: relative; right: unset; top: unset; }",
  ".framer-gxEXg.framer-v-qq7o9z .framer-jxagyo-container { order: 1; }",
  ".framer-gxEXg.framer-v-qq7o9z .framer-12dkhc1-container { bottom: unset; left: unset; order: 0; position: relative; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 800
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"],"constraints":[null,null,"100vh",null]},"TpR7tx10J":{"layout":["fixed","auto"],"constraints":[null,null,"100vh",null]},"yEk2784iI":{"layout":["fixed","auto"],"constraints":[null,null,"100vh",null]}}}
 * @framerVariables {"TkbnSs_QY":"serviceName1","YsJaFxlxJ":"serviceContent1","IjTSo9v8a":"image1","q5JoCbVah":"link1","NQUvPF0Ed":"serviceName2","G07aaR7mP":"serviceContent2","kVkM2Vize":"image2","c9JDpgSaj":"link2","bT7VFLkwN":"serviceName3","tUK9QKRfm":"serviceContent3","MAolvu_Uz":"image3","lb_NSLyCc":"cTAButton","jbnk6z7au":"link3","gyWOQ3Y5L":"newTabLinkOpen","WrxRQnwtW":"_1ScrollSection1","kmAs_AL71":"_1ScrollSection2","ry4V6X50J":"_1ScrollSection3","uJ3k_3FrD":"_1ScrollSection4","I1EwIDyNd":"_2ScrollSection1","qk_7shWiw":"_2ScrollSection2","yz6Azgs5e":"_2ScrollSection3","QZeLnSM0X":"_2ScrollSection4","FQrrRv3Xn":"_3ScrollSection1","KoyyAx70J":"_3ScrollSection2","tWgYBJMqd":"_3ScrollSection3","u5H2OkbTf":"_3ScrollSection4"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerwKkGQAcuS = withCSS(Component, css, "framer-gxEXg");
export default FramerwKkGQAcuS;
FramerwKkGQAcuS.displayName = "Scroll Flip Card";
FramerwKkGQAcuS.defaultProps = { height: 800, width: 1200 };
addPropertyControls(FramerwKkGQAcuS, {
  variant: {
    options: ["NJ2mYgZiy", "TpR7tx10J", "yEk2784iI"],
    optionTitles: ["Desktop", "Tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  TkbnSs_QY: {
    defaultValue: "Branding & Identity",
    displayTextArea: false,
    title: "Service Name 1",
    type: ControlType.String,
  },
  onTkbnSs_QYChange: { changes: "TkbnSs_QY", type: ControlType.ChangeHandler },
  YsJaFxlxJ: {
    defaultValue:
      "Build distinctive brands through strategy, identity, and messaging that create trust and meaningful audience connections now.",
    displayTextArea: true,
    title: "Service Content 1",
    type: ControlType.String,
  },
  onYsJaFxlxJChange: { changes: "YsJaFxlxJ", type: ControlType.ChangeHandler },
  IjTSo9v8a: {
    __defaultAssetReference:
      "data:framer/asset-reference,tUkDeSIXGHUoQm8mfXzM7PvqB8Q.png?originalFilename=image.png&width=686&height=755",
    title: "Image 1",
    type: ControlType.ResponsiveImage,
  },
  q5JoCbVah: {
    description: "_________________",
    title: "Link 1",
    type: ControlType.Link,
  },
  NQUvPF0Ed: {
    defaultValue: "Web Design & Dev",
    displayTextArea: false,
    title: "Service Name 2",
    type: ControlType.String,
  },
  onNQUvPF0EdChange: { changes: "NQUvPF0Ed", type: ControlType.ChangeHandler },
  G07aaR7mP: {
    defaultValue:
      "Design and develop modern websites with seamless experiences that engage visitors and turn interactions into growth at scale.",
    displayTextArea: true,
    title: "Service Content 2",
    type: ControlType.String,
  },
  onG07aaR7mPChange: { changes: "G07aaR7mP", type: ControlType.ChangeHandler },
  kVkM2Vize: {
    __defaultAssetReference:
      "data:framer/asset-reference,A4kZ4JKrKRQB47BZsV6CXyJCwA.png?originalFilename=QmS2HmAfw6QG5qBNhy42PAumHfquXv2fBTa8MjvzetLDNy%3Fauto%3Dformat%26w%3D1200.png&width=1200&height=673",
    title: "Image 2",
    type: ControlType.ResponsiveImage,
  },
  c9JDpgSaj: {
    description: "_________________",
    title: "Link 2",
    type: ControlType.Link,
  },
  bT7VFLkwN: {
    defaultValue: "Creative Production",
    displayTextArea: false,
    title: "Service Name 3",
    type: ControlType.String,
  },
  onbT7VFLkwNChange: { changes: "bT7VFLkwN", type: ControlType.ChangeHandler },
  tUK9QKRfm: {
    defaultValue:
      "Create impactful visual content through storytelling and production that captures attention across every platform every day.",
    displayTextArea: true,
    title: "Service Content 3",
    type: ControlType.String,
  },
  ontUK9QKRfmChange: { changes: "tUK9QKRfm", type: ControlType.ChangeHandler },
  MAolvu_Uz: {
    __defaultAssetReference:
      "data:framer/asset-reference,aX7OzhXTeeu9KoHilGJmEuZTbY.png?originalFilename=QmQ1PTpuFGXa3diTad4giqm9vKjucPji4GyEz8LM9ot9pn%3Fauto%3Dformat%26w%3D1200.png&width=1200&height=799",
    title: "Image 3",
    type: ControlType.ResponsiveImage,
  },
  lb_NSLyCc: {
    defaultValue: "Know More",
    displayTextArea: false,
    title: "CTA Button",
    type: ControlType.String,
  },
  onlb_NSLyCcChange: { changes: "lb_NSLyCc", type: ControlType.ChangeHandler },
  jbnk6z7au: {
    description: "_________________",
    title: "Link 3",
    type: ControlType.Link,
  },
  gyWOQ3Y5L: {
    defaultValue: true,
    description:
      "_________________\n\nMade with ❤️ by [Soyeb](https://framer.link/project)",
    title: "New Tab - Link Open",
    type: ControlType.Boolean,
  },
  ongyWOQ3Y5LChange: { changes: "gyWOQ3Y5L", type: ControlType.ChangeHandler },
  WrxRQnwtW: {
    title: "1 - Scroll Section 1",
    type: ControlType.ScrollSectionRef,
  },
  kmAs_AL71: {
    title: "1 - Scroll Section 2",
    type: ControlType.ScrollSectionRef,
  },
  ry4V6X50J: {
    title: "1 - Scroll Section 3",
    type: ControlType.ScrollSectionRef,
  },
  uJ3k_3FrD: {
    title: "1 - Scroll Section 4",
    type: ControlType.ScrollSectionRef,
  },
  I1EwIDyNd: {
    title: "2 - Scroll Section 1",
    type: ControlType.ScrollSectionRef,
  },
  qk_7shWiw: {
    title: "2 - Scroll Section 2",
    type: ControlType.ScrollSectionRef,
  },
  yz6Azgs5e: {
    title: "2 - Scroll Section 3",
    type: ControlType.ScrollSectionRef,
  },
  QZeLnSM0X: {
    title: "2 - Scroll Section 4",
    type: ControlType.ScrollSectionRef,
  },
  FQrrRv3Xn: {
    title: "3 - Scroll Section 1",
    type: ControlType.ScrollSectionRef,
  },
  KoyyAx70J: {
    title: "3 - Scroll Section 2",
    type: ControlType.ScrollSectionRef,
  },
  tWgYBJMqd: {
    title: "3 - Scroll Section 3",
    type: ControlType.ScrollSectionRef,
  },
  u5H2OkbTf: {
    title: "3 - Scroll Section 4",
    type: ControlType.ScrollSectionRef,
  },
});
addFonts(
  FramerwKkGQAcuS,
  [{ explicitInter: true, fonts: [] }, ...CardWrapFonts],
  { supportsExplicitInterCodegen: true },
);
FramerwKkGQAcuS.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([forwardLoader(CardWrap, {}, context)]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerwKkGQAcuS",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerVariables:
          '{"TkbnSs_QY":"serviceName1","YsJaFxlxJ":"serviceContent1","IjTSo9v8a":"image1","q5JoCbVah":"link1","NQUvPF0Ed":"serviceName2","G07aaR7mP":"serviceContent2","kVkM2Vize":"image2","c9JDpgSaj":"link2","bT7VFLkwN":"serviceName3","tUK9QKRfm":"serviceContent3","MAolvu_Uz":"image3","lb_NSLyCc":"cTAButton","jbnk6z7au":"link3","gyWOQ3Y5L":"newTabLinkOpen","WrxRQnwtW":"_1ScrollSection1","kmAs_AL71":"_1ScrollSection2","ry4V6X50J":"_1ScrollSection3","uJ3k_3FrD":"_1ScrollSection4","I1EwIDyNd":"_2ScrollSection1","qk_7shWiw":"_2ScrollSection2","yz6Azgs5e":"_2ScrollSection3","QZeLnSM0X":"_2ScrollSection4","FQrrRv3Xn":"_3ScrollSection1","KoyyAx70J":"_3ScrollSection2","tWgYBJMqd":"_3ScrollSection3","u5H2OkbTf":"_3ScrollSection4"}',
        framerImmutableVariables: "true",
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
        framerIntrinsicWidth: "1200",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"],"constraints":[null,null,"100vh",null]},"TpR7tx10J":{"layout":["fixed","auto"],"constraints":[null,null,"100vh",null]},"yEk2784iI":{"layout":["fixed","auto"],"constraints":[null,null,"100vh",null]}}}',
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "800",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./wKkGQAcuS.map
