// Generated by Framer (0f5ea8b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCodeBoundaryForOverrides,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import { withPreserve3D } from "https://framerusercontent.com/modules/o2D9I3MsMOxfzQWCEjuP/ZGl34930UQgkYMLCIcSW/Preserve3D.js";
import Front from "https://framerusercontent.com/modules/j3XDhGTfST8hlLpdsQDI/SLlkNwpcNG7v7jAyESpU/g0_cN2LCc.js";
import Back from "https://framerusercontent.com/modules/GfWQvYyUWac6UcMwlAs8/10nEjj2XbPERTHi9NBTz/Q3FCRcZVF.js";
const FrontFonts = getFonts(Front);
const BackFonts = getFonts(Back);
const MotionDivWithPreserve3D1igy0z = withCodeBoundaryForOverrides(motion.div, {
  nodeId: "jtoJiMks3",
  override: withPreserve3D,
  scopeId: "S1fWa2Wkj",
});
const cycleOrder = [
  "jtoJiMks3",
  "NwXfoNbge",
  "iSoBmCH55",
  "LrkCYv9bP",
  "qHGk0G_bg",
  "cSK_6_6ak",
];
const serializationHash = "framer-jqElm";
const variantClassNames = {
  cSK_6_6ak: "framer-v-15wt6ei",
  iSoBmCH55: "framer-v-1xysici",
  jtoJiMks3: "framer-v-1igy0z",
  LrkCYv9bP: "framer-v-1ryjkn",
  NwXfoNbge: "framer-v-1uz095x",
  qHGk0G_bg: "framer-v-u36gi1",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const fALVpL9rl = undefined;
const ChqSxOsiW = undefined;
const bHAFaIL6x = undefined;
const G8Lsht7iZ = undefined;
const F5dxZeWeY = undefined;
const gN53GihA5 = undefined;
const n3_0W7muj = undefined;
const qYGkNGCLz = undefined;
const V7HSEOkmb = undefined;
const IBaWzeI9Z = undefined;
const E3heAdqO0 = undefined;
const STJFnlkMo = undefined;
const um_tX3Ry9 = undefined;
const H9QNOLhMo = undefined;
const setfALVpL9rl = undefined;
const setChqSxOsiW = undefined;
const setbHAFaIL6x = undefined;
const setG8Lsht7iZ = undefined;
const setn3_0W7muj = undefined;
const setIBaWzeI9Z = undefined;
const setum_tX3Ry9 = undefined;
const setH9QNOLhMo = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "First Card - Back": "LrkCYv9bP",
  "First Card - Front": "jtoJiMks3",
  "Second Card - Back": "qHGk0G_bg",
  "Second Card - Front": "NwXfoNbge",
  "Third Card - Back": "cSK_6_6ak",
  "Third Card - Front": "iSoBmCH55",
};
const Variants = motion.create(React.Fragment);
const useStateVariable = (externalState, setExternalState) => {
  const [internalState, setInternalState] = React.useState(externalState);
  const [previousExternalState, setPreviousExternalState] =
    React.useState(externalState);
  if (setExternalState) {
    return [externalState, setExternalState];
  }
  if (externalState !== previousExternalState) {
    setInternalState(externalState);
    setPreviousExternalState(externalState);
  }
  return [internalState, setInternalState];
};
const getProps = ({
  cTAButton,
  height,
  id,
  image1,
  image2,
  image3,
  link1,
  link2,
  link3,
  newTab,
  serviceContent1,
  serviceContent2,
  serviceContent3,
  serviceName1,
  serviceName2,
  serviceName3,
  width,
  ...props
}) => {
  return {
    ...props,
    bHAFaIL6x: serviceName3 ?? props.bHAFaIL6x ?? "Creative Production",
    ChqSxOsiW: serviceName2 ?? props.ChqSxOsiW ?? "Web Design & Dev",
    E3heAdqO0: image3 ??
      props.E3heAdqO0 ?? {
        pixelHeight: 799,
        pixelWidth: 1200,
        src: "https://framerusercontent.com/images/aX7OzhXTeeu9KoHilGJmEuZTbY.png?width=1200&height=799",
        srcSet:
          "https://framerusercontent.com/images/aX7OzhXTeeu9KoHilGJmEuZTbY.png?scale-down-to=512&width=1200&height=799 512w,https://framerusercontent.com/images/aX7OzhXTeeu9KoHilGJmEuZTbY.png?scale-down-to=1024&width=1200&height=799 1024w,https://framerusercontent.com/images/aX7OzhXTeeu9KoHilGJmEuZTbY.png?width=1200&height=799 1200w",
      },
    F5dxZeWeY: image1 ??
      props.F5dxZeWeY ?? {
        pixelHeight: 755,
        pixelWidth: 686,
        src: "https://framerusercontent.com/images/tUkDeSIXGHUoQm8mfXzM7PvqB8Q.png?width=686&height=755",
        srcSet:
          "https://framerusercontent.com/images/tUkDeSIXGHUoQm8mfXzM7PvqB8Q.png?width=686&height=755 686w",
      },
    fALVpL9rl: serviceName1 ?? props.fALVpL9rl ?? "Branding & Identity",
    G8Lsht7iZ:
      serviceContent1 ??
      props.G8Lsht7iZ ??
      "Build distinctive brands through strategy, identity, and messaging that create trust and meaningful audience connections now.",
    gN53GihA5: link1 ?? props.gN53GihA5,
    H9QNOLhMo: newTab ?? props.H9QNOLhMo ?? true,
    IBaWzeI9Z:
      serviceContent3 ??
      props.IBaWzeI9Z ??
      "Create impactful visual content through storytelling and production that captures attention across every platform every day.",
    n3_0W7muj:
      serviceContent2 ??
      props.n3_0W7muj ??
      "Design and develop modern websites with seamless experiences that engage visitors and turn interactions into growth at scale.",
    qYGkNGCLz: image2 ??
      props.qYGkNGCLz ?? {
        pixelHeight: 673,
        pixelWidth: 1200,
        src: "https://framerusercontent.com/images/A4kZ4JKrKRQB47BZsV6CXyJCwA.png?width=1200&height=673",
        srcSet:
          "https://framerusercontent.com/images/A4kZ4JKrKRQB47BZsV6CXyJCwA.png?scale-down-to=512&width=1200&height=673 512w,https://framerusercontent.com/images/A4kZ4JKrKRQB47BZsV6CXyJCwA.png?scale-down-to=1024&width=1200&height=673 1024w,https://framerusercontent.com/images/A4kZ4JKrKRQB47BZsV6CXyJCwA.png?width=1200&height=673 1200w",
      },
    STJFnlkMo: link3 ?? props.STJFnlkMo,
    um_tX3Ry9: cTAButton ?? props.um_tX3Ry9 ?? "Know More",
    V7HSEOkmb: link2 ?? props.V7HSEOkmb,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "jtoJiMks3",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    fALVpL9rl: externalfALVpL9rl,
    onfALVpL9rlChange: setExternalfALVpL9rl,
    G8Lsht7iZ: externalG8Lsht7iZ,
    onG8Lsht7iZChange: setExternalG8Lsht7iZ,
    F5dxZeWeY,
    gN53GihA5,
    ChqSxOsiW: externalChqSxOsiW,
    onChqSxOsiWChange: setExternalChqSxOsiW,
    n3_0W7muj: externaln3_0W7muj,
    onn3_0W7mujChange: setExternaln3_0W7muj,
    qYGkNGCLz,
    V7HSEOkmb,
    bHAFaIL6x: externalbHAFaIL6x,
    onbHAFaIL6xChange: setExternalbHAFaIL6x,
    IBaWzeI9Z: externalIBaWzeI9Z,
    onIBaWzeI9ZChange: setExternalIBaWzeI9Z,
    E3heAdqO0,
    STJFnlkMo,
    um_tX3Ry9: externalum_tX3Ry9,
    onum_tX3Ry9Change: setExternalum_tX3Ry9,
    H9QNOLhMo: externalH9QNOLhMo,
    onH9QNOLhMoChange: setExternalH9QNOLhMo,
    ...restProps
  } = getProps(props);
  const [fALVpL9rl, setfALVpL9rl] = useStateVariable(
    externalfALVpL9rl,
    setExternalfALVpL9rl,
  );
  const [G8Lsht7iZ, setG8Lsht7iZ] = useStateVariable(
    externalG8Lsht7iZ,
    setExternalG8Lsht7iZ,
  );
  const [ChqSxOsiW, setChqSxOsiW] = useStateVariable(
    externalChqSxOsiW,
    setExternalChqSxOsiW,
  );
  const [n3_0W7muj, setn3_0W7muj] = useStateVariable(
    externaln3_0W7muj,
    setExternaln3_0W7muj,
  );
  const [bHAFaIL6x, setbHAFaIL6x] = useStateVariable(
    externalbHAFaIL6x,
    setExternalbHAFaIL6x,
  );
  const [IBaWzeI9Z, setIBaWzeI9Z] = useStateVariable(
    externalIBaWzeI9Z,
    setExternalIBaWzeI9Z,
  );
  const [um_tX3Ry9, setum_tX3Ry9] = useStateVariable(
    externalum_tX3Ry9,
    setExternalum_tX3Ry9,
  );
  const [H9QNOLhMo, setH9QNOLhMo] = useStateVariable(
    externalH9QNOLhMo,
    setExternalH9QNOLhMo,
  );
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "jtoJiMks3",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(MotionDivWithPreserve3D1igy0z, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1igy0z",
            className,
            classNames,
          ),
          "data-framer-name": "First Card - Front",
          layoutDependency: layoutDependency,
          layoutId: "jtoJiMks3",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              cSK_6_6ak: { "data-framer-name": "Third Card - Back" },
              iSoBmCH55: { "data-framer-name": "Third Card - Front" },
              LrkCYv9bP: { "data-framer-name": "First Card - Back" },
              NwXfoNbge: { "data-framer-name": "Second Card - Front" },
              qHGk0G_bg: { "data-framer-name": "Second Card - Back" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-zvpewg",
            "data-framer-name": "Card",
            layoutDependency: layoutDependency,
            layoutId: "k16gWF0nf",
            style: { rotateY: 0, transformPerspective: 1e3 },
            variants: {
              cSK_6_6ak: { rotateY: 180 },
              LrkCYv9bP: { rotateY: 180 },
              qHGk0G_bg: { rotateY: 180 },
            },
            children: [
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1nlvvbc",
                "data-framer-name": "Front",
                layoutDependency: layoutDependency,
                layoutId: "VlJamnDSj",
                children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  height: 400,
                  width: "290px",
                  y:
                    (componentViewport?.y || 0) +
                    (0 + ((componentViewport?.height || 400) - 0 - 400) / 2) +
                    0 +
                    0 +
                    0,
                  ...addPropertyOverrides(
                    {
                      cSK_6_6ak: {
                        y:
                          (componentViewport?.y || 0) +
                          (0 +
                            ((componentViewport?.height || 200) - 0 - 400) /
                              2) +
                          0 +
                          0 +
                          0,
                      },
                      iSoBmCH55: {
                        y:
                          (componentViewport?.y || 0) +
                          (0 +
                            ((componentViewport?.height || 200) - 0 - 400) /
                              2) +
                          0 +
                          0 +
                          0,
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                  children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                    className: "framer-1oig0zh-container",
                    "data-framer-name": "Front",
                    layoutDependency: layoutDependency,
                    layoutId: "KuIKO2FT8-container",
                    name: "Front",
                    nodeId: "KuIKO2FT8",
                    rendersWithMotion: true,
                    scopeId: "S1fWa2Wkj",
                    children: /*#__PURE__*/ _jsx(Front, {
                      FCQnGWhRP: fALVpL9rl,
                      height: "100%",
                      i2S_CHuMj: bHAFaIL6x,
                      id: "KuIKO2FT8",
                      layoutId: "KuIKO2FT8",
                      name: "Front",
                      onFCQnGWhRPChange: setfALVpL9rl,
                      oni2S_CHuMjChange: setbHAFaIL6x,
                      onph6f_YLsVChange: setChqSxOsiW,
                      ph6f_YLsV: ChqSxOsiW,
                      style: { height: "100%", width: "100%" },
                      variant: matchVariant("QiM9i8_Bc"),
                      width: "100%",
                      ...addPropertyOverrides(
                        {
                          cSK_6_6ak: { variant: matchVariant("ITIGYR7JF") },
                          iSoBmCH55: { variant: matchVariant("ITIGYR7JF") },
                          NwXfoNbge: { variant: matchVariant("vf1BFm9f3") },
                          qHGk0G_bg: { variant: matchVariant("vf1BFm9f3") },
                        },
                        baseVariant,
                        gestureVariant,
                      ),
                    }),
                  }),
                }),
              }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-152bjlz",
                "data-framer-name": "Back",
                layoutDependency: layoutDependency,
                layoutId: "KwfkgdyZ1",
                style: { rotateY: 180 },
                children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  height: 400,
                  width: "290px",
                  y:
                    (componentViewport?.y || 0) +
                    (0 + ((componentViewport?.height || 400) - 0 - 400) / 2) +
                    0 +
                    0,
                  ...addPropertyOverrides(
                    {
                      cSK_6_6ak: {
                        y:
                          (componentViewport?.y || 0) +
                          (0 +
                            ((componentViewport?.height || 200) - 0 - 400) /
                              2) +
                          0 +
                          0,
                      },
                      iSoBmCH55: {
                        y:
                          (componentViewport?.y || 0) +
                          (0 +
                            ((componentViewport?.height || 200) - 0 - 400) /
                              2) +
                          0 +
                          0,
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                  children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                    className: "framer-yprezc-container",
                    layoutDependency: layoutDependency,
                    layoutId: "ApmnAu3dA-container",
                    nodeId: "ApmnAu3dA",
                    rendersWithMotion: true,
                    scopeId: "S1fWa2Wkj",
                    children: /*#__PURE__*/ _jsx(Back, {
                      AdOmNOw8H: um_tX3Ry9,
                      bEPEa6AkL: n3_0W7muj,
                      BoO_BCD0I: STJFnlkMo,
                      fJoZHx05D: toResponsiveImage(qYGkNGCLz),
                      height: "100%",
                      HeW94dJbG: toResponsiveImage(E3heAdqO0),
                      id: "ApmnAu3dA",
                      jRbA5RsT_: G8Lsht7iZ,
                      l0Sg1qdto: gN53GihA5,
                      layoutId: "ApmnAu3dA",
                      nnDpJtdL9: bHAFaIL6x,
                      ofIgmwkLK: IBaWzeI9Z,
                      onAdOmNOw8HChange: setum_tX3Ry9,
                      onbEPEa6AkLChange: setn3_0W7muj,
                      onjRbA5RsT_Change: setG8Lsht7iZ,
                      onnnDpJtdL9Change: setbHAFaIL6x,
                      onofIgmwkLKChange: setIBaWzeI9Z,
                      onqUm0unYtWChange: setH9QNOLhMo,
                      onXTuzR3jeIChange: setfALVpL9rl,
                      onYSOxW0bAKChange: setChqSxOsiW,
                      qUm0unYtW: H9QNOLhMo,
                      rFjOB1my8: V7HSEOkmb,
                      style: { height: "100%", width: "100%" },
                      variant: matchVariant("fjYqEBVPY"),
                      width: "100%",
                      xL1jjtylo: toResponsiveImage(F5dxZeWeY),
                      XTuzR3jeI: fALVpL9rl,
                      YSOxW0bAK: ChqSxOsiW,
                      ...addPropertyOverrides(
                        {
                          cSK_6_6ak: { variant: matchVariant("oNu5J8jbT") },
                          iSoBmCH55: { variant: matchVariant("oNu5J8jbT") },
                          NwXfoNbge: { variant: matchVariant("TfOlBX2oj") },
                          qHGk0G_bg: { variant: matchVariant("TfOlBX2oj") },
                        },
                        baseVariant,
                        gestureVariant,
                      ),
                    }),
                  }),
                }),
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-jqElm.framer-nu7uat, .framer-jqElm .framer-nu7uat { display: block; }",
  ".framer-jqElm.framer-1igy0z { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-jqElm .framer-zvpewg { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 400px; justify-content: center; overflow: visible; padding: 0px; position: relative; transform-style: preserve-3d; width: 290px; }",
  ".framer-jqElm .framer-1nlvvbc { align-content: center; align-items: center; backface-visibility: hidden; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; z-index: 2; }",
  ".framer-jqElm .framer-1oig0zh-container, .framer-jqElm .framer-yprezc-container { flex: none; height: 400px; position: relative; width: 290px; }",
  ".framer-jqElm .framer-152bjlz { align-content: center; align-items: center; backface-visibility: hidden; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; justify-content: center; left: 0px; overflow: visible; padding: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
  ".framer-jqElm.framer-v-1ryjkn .framer-1nlvvbc, .framer-jqElm.framer-v-u36gi1 .framer-1nlvvbc, .framer-jqElm.framer-v-15wt6ei .framer-1nlvvbc { z-index: 1; }",
  ".framer-jqElm.framer-v-1ryjkn .framer-152bjlz, .framer-jqElm.framer-v-u36gi1 .framer-152bjlz, .framer-jqElm.framer-v-15wt6ei .framer-152bjlz { z-index: 2; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 400
 * @framerIntrinsicWidth 290
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"NwXfoNbge":{"layout":["auto","auto"]},"iSoBmCH55":{"layout":["auto","auto"]},"LrkCYv9bP":{"layout":["auto","auto"]},"qHGk0G_bg":{"layout":["auto","auto"]},"cSK_6_6ak":{"layout":["auto","auto"]}}}
 * @framerVariables {"fALVpL9rl":"serviceName1","G8Lsht7iZ":"serviceContent1","F5dxZeWeY":"image1","gN53GihA5":"link1","ChqSxOsiW":"serviceName2","n3_0W7muj":"serviceContent2","qYGkNGCLz":"image2","V7HSEOkmb":"link2","bHAFaIL6x":"serviceName3","IBaWzeI9Z":"serviceContent3","E3heAdqO0":"image3","STJFnlkMo":"link3","um_tX3Ry9":"cTAButton","H9QNOLhMo":"newTab"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerS1fWa2Wkj = withCSS(Component, css, "framer-jqElm");
export default FramerS1fWa2Wkj;
FramerS1fWa2Wkj.displayName = "Card Wrap";
FramerS1fWa2Wkj.defaultProps = { height: 400, width: 290 };
addPropertyControls(FramerS1fWa2Wkj, {
  variant: {
    options: [
      "jtoJiMks3",
      "NwXfoNbge",
      "iSoBmCH55",
      "LrkCYv9bP",
      "qHGk0G_bg",
      "cSK_6_6ak",
    ],
    optionTitles: [
      "First Card - Front",
      "Second Card - Front",
      "Third Card - Front",
      "First Card - Back",
      "Second Card - Back",
      "Third Card - Back",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
  fALVpL9rl: {
    defaultValue: "Branding & Identity",
    displayTextArea: false,
    title: "Service Name 1",
    type: ControlType.String,
  },
  onfALVpL9rlChange: { changes: "fALVpL9rl", type: ControlType.ChangeHandler },
  G8Lsht7iZ: {
    defaultValue:
      "Build distinctive brands through strategy, identity, and messaging that create trust and meaningful audience connections now.",
    displayTextArea: true,
    title: "Service Content 1",
    type: ControlType.String,
  },
  onG8Lsht7iZChange: { changes: "G8Lsht7iZ", type: ControlType.ChangeHandler },
  F5dxZeWeY: {
    __defaultAssetReference:
      "data:framer/asset-reference,tUkDeSIXGHUoQm8mfXzM7PvqB8Q.png?originalFilename=image.png&width=686&height=755",
    title: "Image 1",
    type: ControlType.ResponsiveImage,
  },
  gN53GihA5: { title: "Link 1", type: ControlType.Link },
  ChqSxOsiW: {
    defaultValue: "Web Design & Dev",
    displayTextArea: false,
    title: "Service Name 2",
    type: ControlType.String,
  },
  onChqSxOsiWChange: { changes: "ChqSxOsiW", type: ControlType.ChangeHandler },
  n3_0W7muj: {
    defaultValue:
      "Design and develop modern websites with seamless experiences that engage visitors and turn interactions into growth at scale.",
    displayTextArea: true,
    title: "Service Content 2",
    type: ControlType.String,
  },
  onn3_0W7mujChange: { changes: "n3_0W7muj", type: ControlType.ChangeHandler },
  qYGkNGCLz: {
    __defaultAssetReference:
      "data:framer/asset-reference,A4kZ4JKrKRQB47BZsV6CXyJCwA.png?originalFilename=QmS2HmAfw6QG5qBNhy42PAumHfquXv2fBTa8MjvzetLDNy%3Fauto%3Dformat%26w%3D1200.png&width=1200&height=673",
    title: "Image 2",
    type: ControlType.ResponsiveImage,
  },
  V7HSEOkmb: { title: "Link 2", type: ControlType.Link },
  bHAFaIL6x: {
    defaultValue: "Creative Production",
    displayTextArea: false,
    title: "Service Name 3",
    type: ControlType.String,
  },
  onbHAFaIL6xChange: { changes: "bHAFaIL6x", type: ControlType.ChangeHandler },
  IBaWzeI9Z: {
    defaultValue:
      "Create impactful visual content through storytelling and production that captures attention across every platform every day.",
    displayTextArea: true,
    title: "Service Content 3",
    type: ControlType.String,
  },
  onIBaWzeI9ZChange: { changes: "IBaWzeI9Z", type: ControlType.ChangeHandler },
  E3heAdqO0: {
    __defaultAssetReference:
      "data:framer/asset-reference,aX7OzhXTeeu9KoHilGJmEuZTbY.png?originalFilename=QmQ1PTpuFGXa3diTad4giqm9vKjucPji4GyEz8LM9ot9pn%3Fauto%3Dformat%26w%3D1200.png&width=1200&height=799",
    title: "Image 3",
    type: ControlType.ResponsiveImage,
  },
  STJFnlkMo: { title: "Link 3", type: ControlType.Link },
  um_tX3Ry9: {
    defaultValue: "Know More",
    displayTextArea: false,
    title: "CTA Button",
    type: ControlType.String,
  },
  onum_tX3Ry9Change: { changes: "um_tX3Ry9", type: ControlType.ChangeHandler },
  H9QNOLhMo: {
    defaultValue: true,
    title: "New Tab",
    type: ControlType.Boolean,
  },
  onH9QNOLhMoChange: { changes: "H9QNOLhMo", type: ControlType.ChangeHandler },
});
addFonts(
  FramerS1fWa2Wkj,
  [{ explicitInter: true, fonts: [] }, ...FrontFonts, ...BackFonts],
  { supportsExplicitInterCodegen: true },
);
FramerS1fWa2Wkj.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([
      forwardLoader(Front, {}, context),
      forwardLoader(Back, {}, context),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerS1fWa2Wkj",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "400",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"NwXfoNbge":{"layout":["auto","auto"]},"iSoBmCH55":{"layout":["auto","auto"]},"LrkCYv9bP":{"layout":["auto","auto"]},"qHGk0G_bg":{"layout":["auto","auto"]},"cSK_6_6ak":{"layout":["auto","auto"]}}}',
        framerIntrinsicWidth: "290",
        framerContractVersion: "1",
        framerVariables:
          '{"fALVpL9rl":"serviceName1","G8Lsht7iZ":"serviceContent1","F5dxZeWeY":"image1","gN53GihA5":"link1","ChqSxOsiW":"serviceName2","n3_0W7muj":"serviceContent2","qYGkNGCLz":"image2","V7HSEOkmb":"link2","bHAFaIL6x":"serviceName3","IBaWzeI9Z":"serviceContent3","E3heAdqO0":"image3","STJFnlkMo":"link3","um_tX3Ry9":"cTAButton","H9QNOLhMo":"newTab"}',
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./S1fWa2Wkj.map
