// Generated by Framer (0f5ea8b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image as Image1,
  Instance,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Shape858 from "https://framerusercontent.com/modules/Q2FTIyhJYzsFTj6Ol33b/DkfTEhmFBhEzjIvjXW2X/zQQZ7fBx8.js";
import Shape975 from "https://framerusercontent.com/modules/vui3bx3IYU0GcBDvQz0F/upAboORNnyX8fdWwz07S/Hnmuv6ppV.js";
import Shape1121 from "https://framerusercontent.com/modules/W8KD3eY8xmML7YK03mJD/r6y3biI1MO4JQCPOY43C/zt3nZUYiD.js";
const cycleOrder = ["fjYqEBVPY", "TfOlBX2oj", "oNu5J8jbT", "jega7zOCl"];
const serializationHash = "framer-5jjmS";
const variantClassNames = {
  fjYqEBVPY: "framer-v-197nmk9",
  jega7zOCl: "framer-v-191pllx",
  oNu5J8jbT: "framer-v-jt2yz6",
  TfOlBX2oj: "framer-v-1h0ge0m",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const XTuzR3jeI = undefined;
const YSOxW0bAK = undefined;
const nnDpJtdL9 = undefined;
const jRbA5RsT_ = undefined;
const bEPEa6AkL = undefined;
const ofIgmwkLK = undefined;
const xL1jjtylo = undefined;
const fJoZHx05D = undefined;
const HeW94dJbG = undefined;
const l0Sg1qdto = undefined;
const qUm0unYtW = undefined;
const rFjOB1my8 = undefined;
const BoO_BCD0I = undefined;
const AdOmNOw8H = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Variant 4": "jega7zOCl",
  First: "fjYqEBVPY",
  Second: "TfOlBX2oj",
  Third: "oNu5J8jbT",
};
const Variants = motion.create(React.Fragment);
const getProps = ({
  cTAButton,
  height,
  id,
  image1,
  image2,
  image3,
  link1,
  link2,
  link3,
  newTab,
  serviceContent1,
  serviceContent2,
  serviceContent3,
  serviceName1,
  serviceName2,
  serviceName3,
  width,
  ...props
}) => {
  return {
    ...props,
    AdOmNOw8H: cTAButton ?? props.AdOmNOw8H ?? "Know More",
    bEPEa6AkL:
      serviceContent2 ??
      props.bEPEa6AkL ??
      "Design and develop modern websites with seamless experiences that engage visitors and turn interactions into growth at scale.",
    BoO_BCD0I: link3 ?? props.BoO_BCD0I,
    fJoZHx05D: image2 ??
      props.fJoZHx05D ?? {
        alt: "",
        pixelHeight: 673,
        pixelWidth: 1200,
        src: "https://framerusercontent.com/images/A4kZ4JKrKRQB47BZsV6CXyJCwA.png?width=1200&height=673",
        srcSet:
          "https://framerusercontent.com/images/A4kZ4JKrKRQB47BZsV6CXyJCwA.png?scale-down-to=512&width=1200&height=673 512w,https://framerusercontent.com/images/A4kZ4JKrKRQB47BZsV6CXyJCwA.png?scale-down-to=1024&width=1200&height=673 1024w,https://framerusercontent.com/images/A4kZ4JKrKRQB47BZsV6CXyJCwA.png?width=1200&height=673 1200w",
      },
    HeW94dJbG: image3 ??
      props.HeW94dJbG ?? {
        alt: "",
        pixelHeight: 799,
        pixelWidth: 1200,
        src: "https://framerusercontent.com/images/aX7OzhXTeeu9KoHilGJmEuZTbY.png?width=1200&height=799",
        srcSet:
          "https://framerusercontent.com/images/aX7OzhXTeeu9KoHilGJmEuZTbY.png?scale-down-to=512&width=1200&height=799 512w,https://framerusercontent.com/images/aX7OzhXTeeu9KoHilGJmEuZTbY.png?scale-down-to=1024&width=1200&height=799 1024w,https://framerusercontent.com/images/aX7OzhXTeeu9KoHilGJmEuZTbY.png?width=1200&height=799 1200w",
      },
    jRbA5RsT_:
      serviceContent1 ??
      props.jRbA5RsT_ ??
      "Build distinctive brands through strategy, identity, and messaging that create trust and meaningful audience connections now.",
    l0Sg1qdto: link1 ?? props.l0Sg1qdto,
    nnDpJtdL9: serviceName3 ?? props.nnDpJtdL9 ?? "Creative Production",
    ofIgmwkLK:
      serviceContent3 ??
      props.ofIgmwkLK ??
      "Create impactful visual content through storytelling and production that captures attention across every platform every day.",
    qUm0unYtW: newTab ?? props.qUm0unYtW ?? true,
    rFjOB1my8: link2 ?? props.rFjOB1my8,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "fjYqEBVPY",
    xL1jjtylo: image1 ??
      props.xL1jjtylo ?? {
        alt: "",
        pixelHeight: 755,
        pixelWidth: 686,
        src: "https://framerusercontent.com/images/tUkDeSIXGHUoQm8mfXzM7PvqB8Q.png?width=686&height=755",
        srcSet:
          "https://framerusercontent.com/images/tUkDeSIXGHUoQm8mfXzM7PvqB8Q.png?width=686&height=755 686w",
      },
    XTuzR3jeI: serviceName1 ?? props.XTuzR3jeI ?? "Branding & Identity",
    YSOxW0bAK: serviceName2 ?? props.YSOxW0bAK ?? "Web Design & Dev",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    XTuzR3jeI,
    jRbA5RsT_,
    xL1jjtylo,
    l0Sg1qdto,
    YSOxW0bAK,
    bEPEa6AkL,
    fJoZHx05D,
    rFjOB1my8,
    nnDpJtdL9,
    ofIgmwkLK,
    HeW94dJbG,
    BoO_BCD0I,
    AdOmNOw8H,
    qUm0unYtW,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "fjYqEBVPY",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-197nmk9",
            className,
            classNames,
          ),
          "data-framer-name": "First",
          layoutDependency: layoutDependency,
          layoutId: "fjYqEBVPY",
          ref: refBinding,
          style: {
            backgroundColor: "rgba(0, 0, 0, 0)",
            borderBottomLeftRadius: 20,
            borderBottomRightRadius: 20,
            borderTopLeftRadius: 20,
            borderTopRightRadius: 20,
            ...style,
          },
          ...addPropertyOverrides(
            {
              jega7zOCl: { "data-framer-name": "Variant 4" },
              oNu5J8jbT: { "data-framer-name": "Third" },
              TfOlBX2oj: { "data-framer-name": "Second" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-12boqyb",
            "data-framer-name": "Wrap",
            layoutDependency: layoutDependency,
            layoutId: "GqN31ltvu",
            style: {
              background:
                "linear-gradient(180deg, rgb(223, 139, 43) 0%, rgb(223, 139, 43) 100%)",
              backgroundColor: "rgb(223, 139, 43)",
              borderBottomLeftRadius: 15.84,
              borderBottomRightRadius: 15.84,
              borderTopLeftRadius: 15.84,
              borderTopRightRadius: 15.84,
            },
            variants: {
              jega7zOCl: {
                background:
                  "linear-gradient(180deg, rgb(84, 184, 51) 0%, rgb(61, 158, 28) 100%)",
                backgroundColor: "rgba(0, 0, 0, 0)",
              },
              oNu5J8jbT: {
                background:
                  "linear-gradient(180deg, rgb(84, 184, 51) 0%, rgb(61, 158, 28) 100%)",
                backgroundColor: "rgba(0, 0, 0, 0)",
              },
              TfOlBX2oj: {
                background:
                  "linear-gradient(180deg, rgb(60, 138, 240) 0%, rgb(54, 120, 207) 100%)",
                backgroundColor: "rgba(0, 0, 0, 0)",
              },
            },
            children: [
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-18t99xl",
                "data-framer-name": "Top Wrap",
                layoutDependency: layoutDependency,
                layoutId: "QpBX1NLgO",
                children: [
                  /*#__PURE__*/ _jsx(Instance, {
                    animated: true,
                    className: "framer-jxahud",
                    Component: Shape1121,
                    "data-framer-name": "Shape",
                    layoutDependency: layoutDependency,
                    layoutId: "looJ04VDD",
                    style: {
                      "--1c2dmy6": "rgba(255, 255, 255, 0.7)",
                      "--clsckg": 24,
                      "--framer-icon-mask-mode": "intersect",
                      "--framer-icon-mask":
                        "linear-gradient(0deg, rgba(0,0,0,0) -66%, rgba(0,0,0,1) 100%) add",
                    },
                    ...addPropertyOverrides(
                      {
                        jega7zOCl: { Component: Shape975 },
                        oNu5J8jbT: { Component: Shape975 },
                        TfOlBX2oj: { Component: Shape858 },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  }),
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-n8e5tl",
                    "data-framer-name": "Content Wrap",
                    layoutDependency: layoutDependency,
                    layoutId: "Wk_gNKO6D",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            dir: "auto",
                            style: {
                              "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                              "--framer-font-size": "20px",
                              "--framer-font-weight": "600",
                              "--framer-letter-spacing": "-0.04em",
                              "--framer-line-height": "1.1em",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                            },
                            children: "Branding & Identity",
                          }),
                        }),
                        className: "framer-1afj7ye",
                        "data-framer-name": "Title",
                        fonts: ["Inter-SemiBold"],
                        layoutDependency: layoutDependency,
                        layoutId: "R4oA8S1Yu",
                        style: {
                          "--extracted-r6o4lv": "rgb(255, 255, 255)",
                          "--framer-paragraph-spacing": "0px",
                        },
                        text: XTuzR3jeI,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            jega7zOCl: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  dir: "auto",
                                  style: {
                                    "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                                    "--framer-font-size": "20px",
                                    "--framer-font-weight": "600",
                                    "--framer-letter-spacing": "-0.04em",
                                    "--framer-line-height": "1.1em",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                                  },
                                  children: "Creative Production",
                                }),
                              }),
                              text: nnDpJtdL9,
                            },
                            oNu5J8jbT: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  dir: "auto",
                                  style: {
                                    "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                                    "--framer-font-size": "20px",
                                    "--framer-font-weight": "600",
                                    "--framer-letter-spacing": "-0.04em",
                                    "--framer-line-height": "1.1em",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                                  },
                                  children: "Creative Production",
                                }),
                              }),
                              text: nnDpJtdL9,
                            },
                            TfOlBX2oj: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  dir: "auto",
                                  style: {
                                    "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                                    "--framer-font-size": "20px",
                                    "--framer-font-weight": "600",
                                    "--framer-letter-spacing": "-0.04em",
                                    "--framer-line-height": "1.1em",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                                  },
                                  children: "Web Design & Dev",
                                }),
                              }),
                              text: YSOxW0bAK,
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        ),
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            dir: "auto",
                            style: {
                              "--font-selector": "SW50ZXItTWVkaXVt",
                              "--framer-font-size": "12px",
                              "--framer-font-weight": "500",
                              "--framer-letter-spacing": "-0.04em",
                              "--framer-line-height": "1.15em",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgba(255, 255, 255, 0.86))",
                            },
                            children:
                              "Asics went 11 with their hello Asics went 11 with their hello Asics went 11 with their helloAsics went 11 with their hello",
                          }),
                        }),
                        className: "framer-7q6fhl",
                        "data-framer-name": "Content",
                        fonts: ["Inter-Medium"],
                        layoutDependency: layoutDependency,
                        layoutId: "BVwJSfQrf",
                        style: {
                          "--extracted-r6o4lv": "rgba(255, 255, 255, 0.86)",
                          "--framer-paragraph-spacing": "0px",
                        },
                        text: jRbA5RsT_,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            jega7zOCl: { text: ofIgmwkLK },
                            oNu5J8jbT: { text: ofIgmwkLK },
                            TfOlBX2oj: { text: bEPEa6AkL },
                          },
                          baseVariant,
                          gestureVariant,
                        ),
                      }),
                    ],
                  }),
                ],
              }),
              /*#__PURE__*/ _jsx(Image1, {
                background: {
                  alt: "",
                  fit: "fill",
                  intrinsicHeight: 755,
                  intrinsicWidth: 686,
                  loading: getLoadingLazyAtYPosition(
                    (componentViewport?.y || 0) +
                      (0 +
                        ((componentViewport?.height || 400) -
                          0 -
                          ((componentViewport?.height || 400) - 0) * 1) /
                          2) +
                      0 +
                      (0 +
                        344.34 +
                        ((((componentViewport?.height || 400) - 0) * 1 -
                          0 -
                          556.15) /
                          1) *
                          1),
                  ),
                  pixelHeight: 755,
                  pixelWidth: 686,
                  sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
                  ...toResponsiveImage(xL1jjtylo),
                },
                className: "framer-44m4ud",
                "data-framer-name": "Image",
                layoutDependency: layoutDependency,
                layoutId: "xY_Wd55kw",
                style: {
                  borderBottomLeftRadius: 16,
                  borderBottomRightRadius: 16,
                  borderTopLeftRadius: 16,
                  borderTopRightRadius: 16,
                },
                ...addPropertyOverrides(
                  {
                    jega7zOCl: {
                      background: {
                        alt: "",
                        fit: "fill",
                        intrinsicHeight: 799,
                        intrinsicWidth: 1200,
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) +
                            (0 +
                              ((componentViewport?.height || 400) -
                                0 -
                                ((componentViewport?.height || 400) - 0) * 1) /
                                2) +
                            0 +
                            (0 +
                              344.34 +
                              ((((componentViewport?.height || 400) - 0) * 1 -
                                0 -
                                556.15) /
                                1) *
                                1),
                        ),
                        pixelHeight: 799,
                        pixelWidth: 1200,
                        sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
                        ...toResponsiveImage(HeW94dJbG),
                      },
                    },
                    oNu5J8jbT: {
                      background: {
                        alt: "",
                        fit: "fill",
                        intrinsicHeight: 799,
                        intrinsicWidth: 1200,
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) +
                            (0 +
                              ((componentViewport?.height || 400) -
                                0 -
                                ((componentViewport?.height || 400) - 0) * 1) /
                                2) +
                            0 +
                            (0 +
                              344.34 +
                              ((((componentViewport?.height || 400) - 0) * 1 -
                                0 -
                                556.15) /
                                1) *
                                1),
                        ),
                        pixelHeight: 799,
                        pixelWidth: 1200,
                        sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
                        ...toResponsiveImage(HeW94dJbG),
                      },
                    },
                    TfOlBX2oj: {
                      background: {
                        alt: "",
                        fit: "fill",
                        intrinsicHeight: 673,
                        intrinsicWidth: 1200,
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) +
                            (0 +
                              ((componentViewport?.height || 400) -
                                0 -
                                ((componentViewport?.height || 400) - 0) * 1) /
                                2) +
                            0 +
                            (0 +
                              344.34 +
                              ((((componentViewport?.height || 400) - 0) * 1 -
                                0 -
                                556.15) /
                                1) *
                                1),
                        ),
                        pixelHeight: 673,
                        pixelWidth: 1200,
                        sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
                        ...toResponsiveImage(fJoZHx05D),
                      },
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
                children: /*#__PURE__*/ _jsx(Link, {
                  href: l0Sg1qdto,
                  motionChild: true,
                  nodeId: "PQFVxJHZg",
                  openInNewTab: qUm0unYtW,
                  scopeId: "Q3FCRcZVF",
                  ...addPropertyOverrides(
                    {
                      jega7zOCl: { href: BoO_BCD0I, openInNewTab: true },
                      oNu5J8jbT: { href: BoO_BCD0I, openInNewTab: true },
                      TfOlBX2oj: { href: rFjOB1my8, openInNewTab: true },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                  children: /*#__PURE__*/ _jsx(motion.a, {
                    className: "framer-16qoqft framer-kvceea",
                    "data-framer-name": "Button",
                    layoutDependency: layoutDependency,
                    layoutId: "PQFVxJHZg",
                    style: {
                      backgroundColor: "rgb(255, 255, 255)",
                      borderBottomLeftRadius: 15.56,
                      borderBottomRightRadius: 15.56,
                      borderTopLeftRadius: 15.56,
                      borderTopRightRadius: 15.56,
                      opacity: 0.9,
                    },
                    children: /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          dir: "auto",
                          style: {
                            "--font-selector": "SW50ZXItTWVkaXVt",
                            "--framer-font-size": "9px",
                            "--framer-font-weight": "500",
                            "--framer-letter-spacing": "-0.04em",
                            "--framer-line-height": "100%",
                          },
                          children: "Know More",
                        }),
                      }),
                      className: "framer-idjk81",
                      "data-framer-name": "Text",
                      fonts: ["Inter-Medium"],
                      layoutDependency: layoutDependency,
                      layoutId: "UgBNtq0ad",
                      style: { "--framer-paragraph-spacing": "0px" },
                      text: AdOmNOw8H,
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                  }),
                }),
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-5jjmS.framer-kvceea, .framer-5jjmS .framer-kvceea { display: block; }",
  ".framer-5jjmS.framer-197nmk9 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 400px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 290px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-5jjmS .framer-12boqyb { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 100%; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-5jjmS .framer-18t99xl { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 23.75px; height: min-content; justify-content: center; overflow: visible; padding: 23.75px 19.8px 0px 19.8px; position: relative; width: 100%; }",
  ".framer-5jjmS .framer-jxahud { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 40px); position: relative; width: 40px; }",
  ".framer-5jjmS .framer-n8e5tl { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 15.84px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-5jjmS .framer-1afj7ye, .framer-5jjmS .framer-7q6fhl { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-5jjmS .framer-44m4ud { flex: none; gap: 0px; height: 212px; overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
  ".framer-5jjmS .framer-16qoqft { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 24px; justify-content: center; left: 18px; overflow: visible; padding: 5.94px 9.9px 5.94px 9.9px; position: absolute; text-decoration: none; top: 168px; width: 69px; }",
  ".framer-5jjmS .framer-idjk81 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-5jjmS.framer-v-191pllx .framer-jxahud { height: var(--framer-aspect-ratio-supported, 102px); }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 400
 * @framerIntrinsicWidth 290
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"TfOlBX2oj":{"layout":["fixed","fixed"]},"oNu5J8jbT":{"layout":["fixed","fixed"]},"jega7zOCl":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"XTuzR3jeI":"serviceName1","jRbA5RsT_":"serviceContent1","xL1jjtylo":"image1","l0Sg1qdto":"link1","YSOxW0bAK":"serviceName2","bEPEa6AkL":"serviceContent2","fJoZHx05D":"image2","rFjOB1my8":"link2","nnDpJtdL9":"serviceName3","ofIgmwkLK":"serviceContent3","HeW94dJbG":"image3","BoO_BCD0I":"link3","AdOmNOw8H":"cTAButton","qUm0unYtW":"newTab"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerQ3FCRcZVF = withCSS(Component, css, "framer-5jjmS");
export default FramerQ3FCRcZVF;
FramerQ3FCRcZVF.displayName = "Back";
FramerQ3FCRcZVF.defaultProps = { height: 400, width: 290 };
addPropertyControls(FramerQ3FCRcZVF, {
  variant: {
    options: ["fjYqEBVPY", "TfOlBX2oj", "oNu5J8jbT", "jega7zOCl"],
    optionTitles: ["First", "Second", "Third", "Variant 4"],
    title: "Variant",
    type: ControlType.Enum,
  },
  XTuzR3jeI: {
    defaultValue: "Branding & Identity",
    displayTextArea: false,
    title: "Service Name 1",
    type: ControlType.String,
  },
  onXTuzR3jeIChange: { changes: "XTuzR3jeI", type: ControlType.ChangeHandler },
  jRbA5RsT_: {
    defaultValue:
      "Build distinctive brands through strategy, identity, and messaging that create trust and meaningful audience connections now.",
    displayTextArea: true,
    title: "Service Content 1",
    type: ControlType.String,
  },
  onjRbA5RsT_Change: { changes: "jRbA5RsT_", type: ControlType.ChangeHandler },
  xL1jjtylo: {
    __defaultAssetReference:
      "data:framer/asset-reference,tUkDeSIXGHUoQm8mfXzM7PvqB8Q.png?originalFilename=image.png&width=686&height=755",
    __vekterDefault: {
      alt: "",
      assetReference:
        "data:framer/asset-reference,tUkDeSIXGHUoQm8mfXzM7PvqB8Q.png?originalFilename=image.png&width=686&height=755",
    },
    title: "Image 1",
    type: ControlType.ResponsiveImage,
  },
  l0Sg1qdto: { title: "Link 1", type: ControlType.Link },
  YSOxW0bAK: {
    defaultValue: "Web Design & Dev",
    displayTextArea: false,
    title: "Service Name 2",
    type: ControlType.String,
  },
  onYSOxW0bAKChange: { changes: "YSOxW0bAK", type: ControlType.ChangeHandler },
  bEPEa6AkL: {
    defaultValue:
      "Design and develop modern websites with seamless experiences that engage visitors and turn interactions into growth at scale.",
    displayTextArea: true,
    title: "Service Content 2",
    type: ControlType.String,
  },
  onbEPEa6AkLChange: { changes: "bEPEa6AkL", type: ControlType.ChangeHandler },
  fJoZHx05D: {
    __defaultAssetReference:
      "data:framer/asset-reference,A4kZ4JKrKRQB47BZsV6CXyJCwA.png?originalFilename=QmS2HmAfw6QG5qBNhy42PAumHfquXv2fBTa8MjvzetLDNy%3Fauto%3Dformat%26w%3D1200.png&width=1200&height=673",
    __vekterDefault: {
      alt: "",
      assetReference:
        "data:framer/asset-reference,A4kZ4JKrKRQB47BZsV6CXyJCwA.png?originalFilename=QmS2HmAfw6QG5qBNhy42PAumHfquXv2fBTa8MjvzetLDNy%3Fauto%3Dformat%26w%3D1200.png&width=1200&height=673",
    },
    title: "Image 2",
    type: ControlType.ResponsiveImage,
  },
  rFjOB1my8: { title: "Link 2", type: ControlType.Link },
  nnDpJtdL9: {
    defaultValue: "Creative Production",
    displayTextArea: false,
    title: "Service Name 3",
    type: ControlType.String,
  },
  onnnDpJtdL9Change: { changes: "nnDpJtdL9", type: ControlType.ChangeHandler },
  ofIgmwkLK: {
    defaultValue:
      "Create impactful visual content through storytelling and production that captures attention across every platform every day.",
    displayTextArea: true,
    title: "Service Content 3",
    type: ControlType.String,
  },
  onofIgmwkLKChange: { changes: "ofIgmwkLK", type: ControlType.ChangeHandler },
  HeW94dJbG: {
    __defaultAssetReference:
      "data:framer/asset-reference,aX7OzhXTeeu9KoHilGJmEuZTbY.png?originalFilename=QmQ1PTpuFGXa3diTad4giqm9vKjucPji4GyEz8LM9ot9pn%3Fauto%3Dformat%26w%3D1200.png&width=1200&height=799",
    __vekterDefault: {
      alt: "",
      assetReference:
        "data:framer/asset-reference,aX7OzhXTeeu9KoHilGJmEuZTbY.png?originalFilename=QmQ1PTpuFGXa3diTad4giqm9vKjucPji4GyEz8LM9ot9pn%3Fauto%3Dformat%26w%3D1200.png&width=1200&height=799",
    },
    title: "Image 3",
    type: ControlType.ResponsiveImage,
  },
  BoO_BCD0I: { title: "Link 3", type: ControlType.Link },
  AdOmNOw8H: {
    defaultValue: "Know More",
    displayTextArea: false,
    title: "CTA Button",
    type: ControlType.String,
  },
  onAdOmNOw8HChange: { changes: "AdOmNOw8H", type: ControlType.ChangeHandler },
  qUm0unYtW: {
    defaultValue: true,
    title: "New Tab",
    type: ControlType.Boolean,
  },
  onqUm0unYtWChange: { changes: "qUm0unYtW", type: ControlType.ChangeHandler },
});
addFonts(
  FramerQ3FCRcZVF,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/yDtI2UI8XcEg1W2je9XPN3Noo.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/UjlFhCnUjxhNfep4oYBPqnEssyo.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
          weight: "500",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerQ3FCRcZVF",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerVariables:
          '{"XTuzR3jeI":"serviceName1","jRbA5RsT_":"serviceContent1","xL1jjtylo":"image1","l0Sg1qdto":"link1","YSOxW0bAK":"serviceName2","bEPEa6AkL":"serviceContent2","fJoZHx05D":"image2","rFjOB1my8":"link2","nnDpJtdL9":"serviceName3","ofIgmwkLK":"serviceContent3","HeW94dJbG":"image3","BoO_BCD0I":"link3","AdOmNOw8H":"cTAButton","qUm0unYtW":"newTab"}',
        framerIntrinsicHeight: "400",
        framerIntrinsicWidth: "290",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"TfOlBX2oj":{"layout":["fixed","fixed"]},"oNu5J8jbT":{"layout":["fixed","fixed"]},"jega7zOCl":{"layout":["fixed","fixed"]}}}',
        framerColorSyntax: "true",
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerComponentViewportWidth: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./Q3FCRcZVF.map
